server:
  port: 9001
  
spring:
  main:
    allow-circular-references: true
  application:
    name: Website-Blog
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chenet_website?useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      jedis:
        pool:
          max-active: 50
          max-wait: 3000
          max-idle: 20
          min-idle: 2
      timeout: 5000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  level:
    root: error
    pers.website: error
  file:
    name: logs/website-blog-dev.log

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl